let allMusic = [

    {
        name: "Asheqi Angar ki Birai",
        writer: "Mir Saleem / Irfan Ali Taj / Zoe Viccaji",
        singer: "Irfan A. Taj / Zoe Viccaji",
        lyricsFile: "asheqi_angar.txt",
    },
    {
        name: "Dunya Ju Baso",
        writer: "Irfan Ali Taj",
        singer: "Irfan Ali Taj / Zoe Viccaji",
        lyricsFile: "dunya_ju_baso.txt",
    },
    {
        name: "Awa Ta Dunyo Pechitam",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "awa_ta_dunyo_pechitam.txt",
    },
    {
        name: "Ishq Daryah",
        writer: "Irfan Ali Taj",
        singer: "Irfan Ali Taj",
        lyricsFile: "ishq_daryah.txt",
    },
    {
        name: "Khosh Bigim",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "khosh_bigim.txt",
    },
    {
        name: "Scholote Biniyan Ma Xano Yaraan",
        writer: "Abdul Hayat",
        singer: "Unknown",
        lyricsFile: "scholote_biniyan.txt",
    },  
    {
        name: "Dashtu Sehra Asum Thrushni Armaan o sum",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "dashtu_sehra_asum.txt",
    },   
    {
        name: "Payan Alanio Lowah",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "lowah.txt",
    },  
    {
        name: "Xan Sadaqa Ta Cheer Golo Sora",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "xan_sadaqa_ta_cheer_golo_sora.txt",
    },  
    {
        name: "Hase Wa Kya Zindagi Sukoon E Darbat Ki No Hoi",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "hase_wa_kya_zindagi.txt",
    },  
    {
        name: "Bas E Kashkol Bas E Xindaan",
        writer: "Faizan Ali Faizan",
        singer: "Unknown",
        lyricsFile: "bas_e_kashkol_bas_e_xindaan.txt",
    }, 
    {
        name: "Berune Khana",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "beruneKhana.txt",
    },
    {
        name: "Ta Husno",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "taHusno.txt",
    }, 
    {
        name: "Wesalo Mas",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "wesaloMas.txt",
    },  
    {
        name: "Kura Ki Arzu Re Newashin Boyan",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "kuraKiArzuReNewashinBoyan.txt",
    }, 
    {
        name: "Ta Namo Neweshi",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "taNamoNewashi.txt",
    }, 
    {
        name: "Sarhad Wathana",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "sarhadWathana.txt",
    }, 
    {
        name: "Girwano E Nas",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "girwanoENas.txt",
    }, 
    {
        name: "Ghoru (Nane Nane Afhera Ka Goyan)",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "ghoru.txt",
    }, 
    {
        name: "Nano Begal",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "nanoBegal.txt",
    }, 
    {
        name: "Ashoor Jan",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "ashurJan.txt",
    }, 
    {
        name: "Nan Doshi",
        writer: "Unknown",
        singer: "Unknown",
        lyricsFile: "nanDoshi.txt",
    }, 
    {
        name: "Rustam o Dani",
        writer: "Rustam",
        singer: "Baba Fatahud Din",
        lyricsFile: "rustamODani.txt",
    }, 
    {
        name: "E Kharkar Naswar Peshako Dust Birai",
        writer: "Iqbal Uddin Sahar",
        singer: "Unknown",
        lyricsFile: "eKharkar.txt",
    }, 
    {
        name: "Mashriqa Yor E Nisseer Awa No Bom",
        writer: "Shaukat Ali",
        singer: "Ansar Elahi",
        lyricsFile: "awaNoBom.txt",
    }, 
    ];
